name: Unit tests

on:
  push:
    branches: [openSUSE/release/3006.0]
  pull_request:
    branches: [openSUSE/release/3006.0]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Salt
        uses: actions/checkout@v4
      - name: Run unit tests
        container:
          image: registry.opensuse.orgsystemsmanagement/saltstack/products/testing/containers/leap15.5/containers/salt-testsuite-github:leap15.5
          volumes:
            - salt:/code

        run: |
          salt-test --skiplist https://raw.githubusercontent.com/openSUSE/salt-test-skiplist/main/skipped_tests.toml \
            --directory /code --package-flavor classic unit
